keys:
  # This key is given to the platform at installation time.
  # Later, our tool can use LTI Advantage services (like the
  # assignment and grade service) by sending a request to the
  # platform signed with our private key
  public:
    kty: RSA
    e: AQAB
    n: 2yaSszl0jSbUyKBhsY5HX6RIFqAxV8rn1qOXsll34wpwTZ_35JpyiTEv4aP0Bp6E8q6YoKfrVE3klf9sL4aAY4nev7G83FUjy5NRZ-dBY1SYCZYaM3GqZMgCiNdZ7K_HWD9ddc0nAm7h4RUVvqtYU0klMOnIjDU6n6x2s2gdMi_4wcK37OIhlig5ZzJUXERNMrAUMzkHHTTxWEuHRo92b5Lg0ahMkWZpl3ltJAaZgqXWQbt0RCBgcrL3cIbRuqFKU7Uz1lEIjYxmSWH6D0WVX6TSvDvBAWxYs_N2Xyf9XlvOtKZf4PA_TxFSL7TMCUuf-rUMUawkzI7Ia3tq2QglAw
    kid: "2020-10-27T22:58:11Z"
    alg: RS256
    use: sig
  # For illustration purposes only! Please don't
  # store your private key in a public config file.
  #
  # This key is used to sign requests to retrieve access tokens
  # from the platform that allow our tool to use LTI Advantage
  # services.
  #
  # This key is also used to decrypt the values from the experimental
  # LTI Storage Service in Canvas LMS
  private:
    kty: :RSA
    e: AQAB
    n: 2yaSszl0jSbUyKBhsY5HX6RIFqAxV8rn1qOXsll34wpwTZ_35JpyiTEv4aP0Bp6E8q6YoKfrVE3klf9sL4aAY4nev7G83FUjy5NRZ-dBY1SYCZYaM3GqZMgCiNdZ7K_HWD9ddc0nAm7h4RUVvqtYU0klMOnIjDU6n6x2s2gdMi_4wcK37OIhlig5ZzJUXERNMrAUMzkHHTTxWEuHRo92b5Lg0ahMkWZpl3ltJAaZgqXWQbt0RCBgcrL3cIbRuqFKU7Uz1lEIjYxmSWH6D0WVX6TSvDvBAWxYs_N2Xyf9XlvOtKZf4PA_TxFSL7TMCUuf-rUMUawkzI7Ia3tq2QglAw
    kid: "2020-10-27T22:58:11Z"
    alg: RS256
    use: sig
    d: kEe974cVJ9T35DpK90XP0bTrzRGcSsuIhTRhLAdhObXmqAR4hSX14ELk3i49-5mjt86hJ6xF79P0eZiXFlb78gyT_Sq8R2c6UM3lm32R_B52lmEfUN01rHJN0N_PEVfM61mUY3k0hJKR3cku7sAKP5L5jFFuOnjU5sj5wTX7es0Ik2IkgMiohWiGIoGpaWtbwrNFnBaV86bREMLI5zBLjeLfwPy0km8NdjamwKk2C1jgICBQ-Peh2fZ12uuH_wi_FXqYnyKlp6NYCVaCduXuBgX_AS6l3Ult6aXGNwvoU_c9xPByOXstfsYxbPI_uklX4WpW9hDjKH5Oh65MyN3QYQ
    p: 8GF5di6jeVqUCCmRcVCG37hX_zmqFuPNdkIR5xcAFNvqjc0f8rH8eSFaCPMiGDrQ7orZsQTCabEVf524mgGFM6mpVNMzef_D1MHaLzfk6_p4AihrR6WtU2dv2vkaTvNlmND6Og-Hfc653LHCp2jxw-SpJPfyOc_uY4jhGO6E0BE
    q: 6WP0XXy8O0x26ikneGPcfKYVXfyZ1mI7YwxILQpMYor2fApr6_ibwtPaz0WI0KPL_BbImXDDaTFDqgWlFtT8RiPyKvuGeZcTKyjniaOPgTvPArfFifQ1wsBoxBn7q_xnrDneaCznHArWG6OBRxPK_78BTIDYQk20-28z9qgNN9M
    dp: tGWCgNXJawY199YyR2bWgUjYCTseUaVOCUTWKKYTMpRD930MT9eRENqdtf-5A5QIPizH6FgZCraR2r7jzff8HeRipr0FcbYnIiEE-9CnpQzISV5J_G_ynpgO0reFLeDtyvxx_WawGRMuWtiwq3BPl-KfqZXGG-rXDa2ouEwwMfE
    dq: 0vOJmEZ6TI7cnOH9zw9T50am4YDD-8ZmLyyWwD8is58vEwbIbU0UXJDooZgUBaFHat-dCTOnLJles3rOsUhpjWxIIxmdfqFSrhwWy42O1ByfC7HXVs3pGdKX30gs9lL50e2sXTTY37vbsreizf_R6D9YiTGcRrG999WXfkZ_TAk
    qi: n6hmEWOvHwegv0oMGsp7i7kZrxsIkRf4USjtf3-CB7cnb7dM4qDMo2gzkrqJAfve9GrO4VQquqZx_oxQAk99_B5EfWso2qKUPWMN8kt0zEq6KEzrw2C_Q4F9DuTDbMv715vsUi0kRnwejlwT-0vnEbvtfvAOeQQ9rTz7AmjnDtc

# The client ID issued to our tool by the platform
client_id: 10000000000057

# The endpoint to which the tool should make the authentication
# request (the second leg in the LTI 1.3 launch)
authentication_endpoint: http://shard1.web.canvas-lms.docker/api/lti/authorize_redirect

# The endpoint the platform's public JWKs are available at. This keyset
# is used to verify the signature of id_tokens in the final leg of
# the LTI 1.3 launch
public_jwks_endpoint: http://172.26.0.5:80/api/lti/security/jwks